In [5]:
import sys
!{sys.executable} -m pip install pyupbit

Collecting pyupbit
  Downloading pyupbit-0.2.34-py3-none-any.whl (24 kB)
Collecting pyjwt>=2.0.0 (from pyupbit)
  Downloading PyJWT-2.10.1-py3-none-any.whl (22 kB)
Requirement already satisfied: pandas in d:\python3.9.5\lib\site-packages (from pyupbit) (2.0.1)
Requirement already satisfied: requests in d:\python3.9.5\lib\site-packages (from pyupbit) (2.29.0)
Collecting websockets (from pyupbit)
  Downloading websockets-15.0.1-cp39-cp39-win_amd64.whl (176 kB)
                                              0.0/176.8 kB ? eta -:--:--
     ------------------------------------- 176.8/176.8 kB 10.4 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python3.9.5\lib\site-packages (from pandas->pyupbit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\python3.9.5\lib\site-packages (from pandas->pyupbit) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in d:\python3.9.5\lib\site-packages (from pandas->pyupbit) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in d:\python3.9.5\lib\site-packages (from pandas->pyupbit) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\python3.9.5\lib\site-packages (from requests->pyupbit) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\python3.9.5\lib\site-packages (from requests->pyupbit) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python3.9.5\lib\site-packages (from requests->pyupbit) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in d:\python3.9.5\lib\site-packages (from requests->pyupbit) (2022.12.7)
Requirement already satisfied: six>=1.5 in d:\python3.9.5\lib\site-packages (from python-dateutil>=2.8.2->pandas->pyupbit) (1.16.0)
Installing collected packages: websockets, pyjwt, pyupbit
Successfully installed pyjwt-2.10.1 pyupbit-0.2.34 websockets-15.0.1

[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: d:\python3.9.5\python.exe -m pip install --upgrade pip

In [16]:
import pyupbit

print(pyupbit.Upbit)

<class 'pyupbit.exchange_api.Upbit'>

In [17]:
import pyupbit

tickers = pyupbit.get_tickers()

In [18]:
tickers

['KRW-BTC',
 'KRW-ETH',
 'BTC-ETH',
 'BTC-XRP',
 'BTC-ETC',
 'BTC-CVC',
 'BTC-DGB',
 'BTC-SC',
 'BTC-SNT',
 'BTC-WAVES',
 'BTC-NMR',
 'BTC-XEM',
 'BTC-QTUM',
 'BTC-BAT',
 'BTC-LSK',
 'BTC-STEEM',
 'BTC-DOGE',
 'BTC-BNT',
 'BTC-XLM',
 'BTC-ARDR',
 'BTC-ARK',
 'BTC-STORJ',
 'BTC-GRS',
 'BTC-RLC',
 'USDT-BTC',
 'USDT-ETH',
 'USDT-XRP',
 'USDT-ETC',
 'KRW-NEO',
 'KRW-MTL',
 'KRW-XRP',
 'KRW-ETC',
 'KRW-SNT',
 'KRW-WAVES',
 'KRW-XEM',
 'KRW-QTUM',
 'KRW-LSK',
 'KRW-STEEM',
 'KRW-XLM',
 'KRW-ARDR',
 'KRW-ARK',
 'KRW-STORJ',
 'KRW-GRS',
 'KRW-ADA',
 'BTC-ADA',
 'BTC-MANA',
 'KRW-POWR',
 'BTC-POWR',
 'USDT-ADA',
 'BTC-DNT',
 'BTC-ZRX',
 'BTC-TRX',
 'BTC-TUSD',
 'BTC-LRC',
 'KRW-ICX',
 'KRW-EOS',
 'USDT-TUSD',
 'KRW-TRX',
 'BTC-POLYX',
 'USDT-SC',
 'USDT-TRX',
 'KRW-SC',
 'KRW-ONT',
 'KRW-ZIL',
 'KRW-POLYX',
 'KRW-ZRX',
 'KRW-LOOM',
 'BTC-BCH',
 'USDT-BCH',
 'KRW-BCH',
 'BTC-HIFI',
 'BTC-LOOM',
 'KRW-BAT',
 'KRW-IOST',
 'USDT-DGB',
 'KRW-CVC',
 'KRW-IQ',
 'KRW-IOTA',
 'BTC-RVN',
 'BTC-GO',
 'BTC-BOUNTY',
 'BTC-ENJ',
 'KRW-HIFI',
 'KRW-ONG',
 'KRW-GAS',
 'BTC-MTL',
 'KRW-BOUNTY',
 'KRW-ELF',
 'USDT-DOGE',
 'USDT-ZRX',
 'USDT-RVN',
 'USDT-BAT',
 'KRW-KNC',
 'BTC-MOC',
 'BTC-ZIL',
 'KRW-BSV',
 'BTC-BSV',
 'BTC-IOST',
 'KRW-THETA',
 'BTC-DENT',
 'KRW-QKC',
 'BTC-ELF',
 'KRW-BTT',
 'BTC-IOTX',
 'BTC-NKN',
 'BTC-META',
 'KRW-MOC',
 'BTC-ANKR',
 'BTC-CRO',
 'KRW-TFUEL',
 'KRW-MANA',
 'KRW-ANKR',
 'BTC-ORBS',
 'BTC-AERGO',
 'KRW-AERGO',
 'KRW-ATOM',
 'KRW-TT',
 'KRW-GAME2',
 'BTC-ATOM',
 'BTC-STPT',
 'KRW-MBL',
 'BTC-EOS',
 'BTC-USDS',
 'BTC-SKY',
 'BTC-BORA',
 'KRW-WAXP',
 'BTC-WAXP',
 'KRW-HBAR',
 'KRW-MED',
 'BTC-MED',
 'BTC-MLK',
 'KRW-MLK',
 'KRW-STPT',
 'BTC-VET',
 'KRW-ORBS',
 'BTC-CHZ',
 'KRW-VET',
 'BTC-PUNDIAI',
 'BTC-OGN',
 'KRW-CHZ',
 'BTC-XTZ',
 'BTC-HIVE',
 'BTC-HBD',
 'BTC-OBSR',
 'BTC-DKA',
 'KRW-STMX',
 'BTC-STMX',
 'BTC-AHT',
 'KRW-DKA',
 'BTC-LINK',
 'KRW-HIVE',
 'KRW-KAVA',
 'BTC-KAVA',
 'KRW-AHT',
 'KRW-LINK',
 'KRW-XTZ',
 'KRW-BORA',
 'BTC-JST',
 'BTC-CHR',
 'BTC-TOKAMAK',
 'KRW-JST',
 'BTC-CTSI',
 'BTC-DOT',
 'KRW-CRO',
 'BTC-COMP',
 'BTC-SXP',
 'BTC-HUNT',
 'KRW-TOKAMAK',
 'BTC-LWA',
 'BTC-CRV',
 'BTC-ALGO',
 'BTC-RSR',
 'KRW-SXP',
 'BTC-OXT',
 'KRW-HUNT',
 'BTC-SAND',
 'BTC-SUN',
 'KRW-DOT',
 'BTC-QTCON',
 'BTC-MVL',
 'KRW-MVL',
 'BTC-REI',
 'BTC-AQT',
 'BTC-AXS',
 'BTC-STRAX',
 'KRW-STRAX',
 'KRW-AQT',
 'BTC-GLM',
 'KRW-GLM',
 'BTC-FCT2',
 'KRW-META',
 'KRW-FCT2',
 'BTC-FIL',
 'BTC-UNI',
 'BTC-INJ',
 'BTC-PROM',
 'BTC-VAL',
 'BTC-PSG',
 'BTC-JUV',
 'BTC-CBK',
 'KRW-CBK',
 'BTC-BFC',
 'BTC-HPO',
 'BTC-CELO',
 'KRW-SAND',
 'KRW-HPO',
 'BTC-IQ',
 'BTC-STX',
 'KRW-DOGE',
 'BTC-NEAR',
 'BTC-AUCTION',
 'BTC-FLOW',
 'BTC-STRIKE',
 'KRW-STRIKE',
 'BTC-PUNDIX',
 'KRW-PUNDIX',
 'KRW-FLOW',
 'KRW-AXS',
 'KRW-STX',
 'BTC-GRT',
 'BTC-SNX',
 'BTC-USDP',
 'KRW-XEC',
 'KRW-SOL',
 'BTC-SOL',
 'KRW-POL',
 'BTC-POL',
 'KRW-AAVE',
 'KRW-1INCH',
 'BTC-AAVE',
 'BTC-1INCH',
 'BTC-MASK',
 'KRW-ALGO',
 'BTC-AUDIO',
 'KRW-NEAR',
 'BTC-YGG',
 'BTC-GTC',
 'BTC-OCEAN',
 'BTC-CTC',
 'BTC-LPT',
 'KRW-AVAX',
 'BTC-AVAX',
 'BTC-IMX',
 'BTC-RENDER',
 'BTC-RLY',
 'KRW-T',
 'BTC-T',
 'KRW-CELO',
 'BTC-RAD',
 'BTC-AGLD',
 'BTC-API3',
 'BTC-ARPA',
 'BTC-ENS',
 'KRW-GMT',
 'BTC-GMT',
 'BTC-APE',
 'BTC-RAY',
 'KRW-APT',
 'BTC-APT',
 'BTC-ACM',
 'BTC-AFC',
 'BTC-ATM',
 'BTC-BAR',
 'BTC-CITY',
 'BTC-INTER',
 'BTC-NAP',
 'KRW-SHIB',
 'BTC-G',
 'BTC-ASTR',
 'BTC-BLUR',
 'KRW-MASK',
 'BTC-ACS',
 'BTC-MAGIC',
 'KRW-ARB',
 'BTC-ARB',
 'KRW-EGLD',
 'BTC-EGLD',
 'KRW-SUI',
 'BTC-SUI',
 'KRW-GRT',
 'KRW-BLUR',
 'BTC-MINA',
 'KRW-IMX',
 'BTC-STG',
 'BTC-SEI',
 'KRW-SEI',
 'BTC-CYBER',
 'BTC-GLMR',
 'KRW-MINA',
 'BTC-ID',
 'BTC-AXL',
 'KRW-CTC',
 'KRW-ASTR',
 'BTC-SPURS',
 'KRW-ID',
 'KRW-PYTH',
 'BTC-PYTH',
 'BTC-ALT',
 'BTC-POKT',
 'USDT-POKT',
 'KRW-MNT',
 'BTC-MNT',
 'USDT-MNT',
 'BTC-BIGTIME',
 'USDT-BIGTIME',
 'KRW-AKT',
 'BTC-AKT',
 'USDT-AKT',
 'KRW-ZETA',
 'BTC-ZETA',
 'USDT-ZETA',
 'BTC-OMNI',
 'USDT-OMNI',
 'BTC-OAS',
 'USDT-OAS',
 'KRW-AUCTION',
 'KRW-STG',
 'KRW-BEAM',
 'BTC-BEAM',
 'USDT-BEAM',
 'KRW-TAIKO',
 'BTC-TAIKO',
 'USDT-TAIKO',
 'KRW-USDT',
 'BTC-USDT',
 'KRW-ONDO',
 'BTC-ONDO',
 'USDT-ONDO',
 'BTC-NEO',
 'USDT-NEO',
 'BTC-GAS',
 'USDT-GAS',
 'BTC-TT',
 'BTC-GAME2',
 'USDT-SOL',
 'KRW-ZRO',
 'BTC-ZRO',
 'USDT-ZRO',
 'KRW-BLAST',
 'BTC-BLAST',
 'USDT-BLAST',
 'KRW-JUP',
 'BTC-JUP',
 'USDT-JUP',
 'KRW-ENS',
 'KRW-G',
 'KRW-PENDLE',
 'BTC-PENDLE',
 'KRW-ATH',
 'BTC-ATH',
 'USDT-BRETT',
 'USDT-PEPE',
 'KRW-USDC',
 'BTC-USDC',
 'USDT-USDC',
 'KRW-UXLINK',
 'BTC-UXLINK',
 'USDT-UXLINK',
 'KRW-BIGTIME',
 'KRW-CKB',
 'BTC-CKB',
 'USDT-CKB',
 'BTC-MEW',
 'USDT-MEW',
 'KRW-W',
 'BTC-W',
 'USDT-W',
 'KRW-CARV',
 'BTC-CARV',
 'USDT-CARV',
 'KRW-INJ',
 'USDT-INJ',
 'KRW-MEW',
 'USDT-BONK',
 'KRW-UNI',
 'USDT-UNI',
 'KRW-SAFE',
 'BTC-SAFE',
 'USDT-SAFE',
 'KRW-DRIFT',
 'BTC-DRIFT',
 'USDT-DRIFT',
 'KRW-AGLD',
 'USDT-AGLD',
 'USDT-AHT',
 'USDT-ARPA',
 'USDT-ASTR',
 'USDT-BNT',
 'USDT-EGLD',
 'USDT-FIL',
 'USDT-LWA',
 'USDT-NEAR',
 'USDT-OXT',
 'USDT-RAD',
 'USDT-XLM',
 'KRW-PEPE',
 'KRW-BONK',
 'BTC-JASMY',
 'USDT-JASMY',
 'BTC-NCT',
 'USDT-NCT',
 'KRW-RENDER',
 'USDT-RENDER',
 'BTC-PUFFER',
 'USDT-PUFFER',
 'BTC-SWELL',
 'USDT-SWELL',
 'KRW-MOVE',
 'BTC-MOVE',
 'USDT-MOVE',
 'KRW-ME',
 'BTC-ME',
 'USDT-ME',
 'KRW-MOCA',
 'BTC-MOCA',
 'USDT-MOCA',
 'KRW-VANA',
 'BTC-VANA',
 'USDT-VANA',
 'KRW-SONIC',
 'BTC-SONIC',
 'USDT-SONIC',
 'KRW-VTHO',
 'USDT-VTHO',
 'KRW-ANIME',
 'BTC-ANIME',
 'USDT-ANIME',
 'KRW-VIRTUAL',
 'BTC-VIRTUAL',
 'USDT-VIRTUAL',
 'BTC-SCR',
 'USDT-SCR',
 'BTC-JTO',
 'USDT-JTO',
 'KRW-BERA',
 'BTC-BERA',
 'USDT-BERA',
 'KRW-LAYER',
 'BTC-LAYER',
 'USDT-LAYER',
 'KRW-TRUMP',
 'BTC-TRUMP',
 'USDT-TRUMP',
 'KRW-JTO',
 'BTC-ARKM',
 'USDT-ARKM',
 'KRW-COW',
 'BTC-COW',
 'USDT-COW',
 'KRW-KAITO',
 'BTC-KAITO',
 'USDT-KAITO',
 'KRW-ARKM']

In [19]:
import pyupbit

tickers = pyupbit.get_tickers('KRW')

print(tickers)

['KRW-BTC', 'KRW-ETH', 'KRW-NEO', 'KRW-MTL', 'KRW-XRP', 'KRW-ETC', 'KRW-SNT', 'KRW-WAVES', 'KRW-XEM', 'KRW-QTUM', 'KRW-LSK', 'KRW-STEEM', 'KRW-XLM', 'KRW-ARDR', 'KRW-ARK', 'KRW-STORJ', 'KRW-GRS', 'KRW-ADA', 'KRW-POWR', 'KRW-ICX', 'KRW-EOS', 'KRW-TRX', 'KRW-SC', 'KRW-ONT', 'KRW-ZIL', 'KRW-POLYX', 'KRW-ZRX', 'KRW-LOOM', 'KRW-BCH', 'KRW-BAT', 'KRW-IOST', 'KRW-CVC', 'KRW-IQ', 'KRW-IOTA', 'KRW-HIFI', 'KRW-ONG', 'KRW-GAS', 'KRW-BOUNTY', 'KRW-ELF', 'KRW-KNC', 'KRW-BSV', 'KRW-THETA', 'KRW-QKC', 'KRW-BTT', 'KRW-MOC', 'KRW-TFUEL', 'KRW-MANA', 'KRW-ANKR', 'KRW-AERGO', 'KRW-ATOM', 'KRW-TT', 'KRW-GAME2', 'KRW-MBL', 'KRW-WAXP', 'KRW-HBAR', 'KRW-MED', 'KRW-MLK', 'KRW-STPT', 'KRW-ORBS', 'KRW-VET', 'KRW-CHZ', 'KRW-STMX', 'KRW-DKA', 'KRW-HIVE', 'KRW-KAVA', 'KRW-AHT', 'KRW-LINK', 'KRW-XTZ', 'KRW-BORA', 'KRW-JST', 'KRW-CRO', 'KRW-TOKAMAK', 'KRW-SXP', 'KRW-HUNT', 'KRW-DOT', 'KRW-MVL', 'KRW-STRAX', 'KRW-AQT', 'KRW-GLM', 'KRW-META', 'KRW-FCT2', 'KRW-CBK', 'KRW-SAND', 'KRW-HPO', 'KRW-DOGE', 'KRW-STRIKE', 'KRW-PUNDIX', 'KRW-FLOW', 'KRW-AXS', 'KRW-STX', 'KRW-XEC', 'KRW-SOL', 'KRW-POL', 'KRW-AAVE', 'KRW-1INCH', 'KRW-ALGO', 'KRW-NEAR', 'KRW-AVAX', 'KRW-T', 'KRW-CELO', 'KRW-GMT', 'KRW-APT', 'KRW-SHIB', 'KRW-MASK', 'KRW-ARB', 'KRW-EGLD', 'KRW-SUI', 'KRW-GRT', 'KRW-BLUR', 'KRW-IMX', 'KRW-SEI', 'KRW-MINA', 'KRW-CTC', 'KRW-ASTR', 'KRW-ID', 'KRW-PYTH', 'KRW-MNT', 'KRW-AKT', 'KRW-ZETA', 'KRW-AUCTION', 'KRW-STG', 'KRW-BEAM', 'KRW-TAIKO', 'KRW-USDT', 'KRW-ONDO', 'KRW-ZRO', 'KRW-BLAST', 'KRW-JUP', 'KRW-ENS', 'KRW-G', 'KRW-PENDLE', 'KRW-ATH', 'KRW-USDC', 'KRW-UXLINK', 'KRW-BIGTIME', 'KRW-CKB', 'KRW-W', 'KRW-CARV', 'KRW-INJ', 'KRW-MEW', 'KRW-UNI', 'KRW-SAFE', 'KRW-DRIFT', 'KRW-AGLD', 'KRW-PEPE', 'KRW-BONK', 'KRW-RENDER', 'KRW-MOVE', 'KRW-ME', 'KRW-MOCA', 'KRW-VANA', 'KRW-SONIC', 'KRW-VTHO', 'KRW-ANIME', 'KRW-VIRTUAL', 'KRW-BERA', 'KRW-LAYER', 'KRW-TRUMP', 'KRW-JTO', 'KRW-COW', 'KRW-KAITO', 'KRW-ARKM']

In [10]:
import pyupbit

BTC = pyupbit.get_current_price('KRW-BTC')

print(BTC)

In [20]:
import pyupbit

df = pyupbit.get_ohlcv('KRW-AUCTION')

In [21]:
df

,open,high,low,close,volume,value
2024-08-31 09:00:00,20720.0,20780.0,19850.0,20060.0,1.976602e+05,4.003455e+09
2024-09-01 09:00:00,20060.0,20060.0,18670.0,18770.0,3.159026e+05,6.088853e+09
2024-09-02 09:00:00,18780.0,19480.0,18570.0,19270.0,2.554795e+05,4.863792e+09
2024-09-03 09:00:00,19280.0,19570.0,17800.0,18000.0,3.229923e+05,6.011913e+09
2024-09-04 09:00:00,18000.0,18290.0,17050.0,17960.0,3.048905e+05,5.391730e+09
...,...,...,...,...,...,...
2025-03-14 09:00:00,38140.0,43410.0,36470.0,40850.0,2.948469e+06,1.163920e+11
2025-03-15 09:00:00,40850.0,40850.0,37010.0,38690.0,1.933403e+06,7.403696e+10
2025-03-16 09:00:00,38630.0,53600.0,37730.0,51250.0,1.060289e+07,5.033753e+11
2025-03-17 09:00:00,51280.0,54630.0,45300.0,47370.0,5.028933e+06,2.492008e+11
2025-03-18 09:00:00,47360.0,49190.0,43530.0,47370.0,2.849300e+06,1.328466e+11

In [22]:
df = pyupbit.get_ohlcv('KRW-AUCTION', interval="minute60", count=2000)

In [23]:
df

,open,high,low,close,volume,value
2024-12-25 10:00:00,32400.0,33400.0,32400.0,32820.0,80732.789146,2.662260e+09
2024-12-25 11:00:00,32910.0,34380.0,32450.0,34250.0,172612.621568,5.753989e+09
2024-12-25 12:00:00,34180.0,34450.0,33020.0,33540.0,177994.440508,6.002489e+09
2024-12-25 13:00:00,33540.0,37870.0,33540.0,36320.0,615396.357220,2.206634e+10
2024-12-25 14:00:00,36410.0,38890.0,34350.0,36050.0,592132.319337,2.179771e+10
...,...,...,...,...,...,...
2025-03-18 18:00:00,45040.0,46750.0,44650.0,45940.0,141759.624353,6.472523e+09
2025-03-18 19:00:00,45950.0,47760.0,45600.0,46980.0,274201.727791,1.283604e+10
2025-03-18 20:00:00,46980.0,48090.0,46450.0,47080.0,194789.937568,9.200709e+09
2025-03-18 21:00:00,47080.0,49190.0,45830.0,48510.0,408561.221152,1.955398e+10
2025-03-18 22:00:00,48540.0,48640.0,47100.0,47490.0,136175.694742,6.504735e+09

In [24]:
df.reset_index()

,index,open,high,low,close,volume,value
0,2024-12-25 10:00:00,32400.0,33400.0,32400.0,32820.0,80732.789146,2.662260e+09
1,2024-12-25 11:00:00,32910.0,34380.0,32450.0,34250.0,172612.621568,5.753989e+09
2,2024-12-25 12:00:00,34180.0,34450.0,33020.0,33540.0,177994.440508,6.002489e+09
3,2024-12-25 13:00:00,33540.0,37870.0,33540.0,36320.0,615396.357220,2.206634e+10
4,2024-12-25 14:00:00,36410.0,38890.0,34350.0,36050.0,592132.319337,2.179771e+10
...,...,...,...,...,...,...,...
1995,2025-03-18 18:00:00,45040.0,46750.0,44650.0,45940.0,141759.624353,6.472523e+09
1996,2025-03-18 19:00:00,45950.0,47760.0,45600.0,46980.0,274201.727791,1.283604e+10
1997,2025-03-18 20:00:00,46980.0,48090.0,46450.0,47080.0,194789.937568,9.200709e+09
1998,2025-03-18 21:00:00,47080.0,49190.0,45830.0,48510.0,408561.221152,1.955398e+10
1999,2025-03-18 22:00:00,48540.0,48640.0,47100.0,47490.0,136175.694742,6.504735e+09

In [13]:
import os,sys
print(os.getcwd())

In [14]:
import os
print(os.environ.get('CONDA_PREFIX'))